### PR TITLE
Update PHP lib

### LINKED ISSUE #1: Add points_products resource

### LINKED ISSUE #2: Add points_purchase resource

### LINKED ISSUE #4: Deprecate spending options and spendings

### PR DESCRIPTION
**Pull request by vladucu**
- deprecate Spending + SpendingOption. fix #4 
- implement PointsProduct resource. fix #1 
- implement PointsPurchase resource. fix #2

### CODE REVIEW

**Comment by vladucu** [comment]
@wcurtis, let me know if you have any comments on this.

**Comment by wcurtis** [comment]
Don't forget to update the VERSION file too
https://github.com/sweettooth/sweettooth-php/blob/master/VERSION

**Comment by vladucu** [comment]
yeap, it's in there :+1:

**Comment by wcurtis** [comment]
Oh! Totally missed that

**Comment by wcurtis** [comment]
Yeah looks good to me. 

Ship it! :rocket:

**Pull request merged**
